[tool.ruff]
target-version = "py310"
line-length = 120
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
preview = true
explicit-preview-rules = true
extend-select = [
    "C", # Complexity
    "E", # PEP8 errors
    "F", # PEP8 formatting
    "I", # Import sorting
    "UP", # Pyupgrade upgrades
    "W", # PEP8 warnings
    "PT009", # Pytest assertions
    "RUF022", # Sorting of __all__
]
ignore = [
    "C901", # Function too complex
    "E501", # Line length (handled by ruff-format)
    "F841", # unused variable
    "UP007", # X | Y style Unions
    "C420", # dict.fromkeys
]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["peft"]
